👨🏽‍💻✨

# NumPy key methods practice questions and solutions.

## Gone through the original task list and its solutions twice. This is my attempt at the same exercises.

For a few of the tasks in this notebook, I had to make reference to solutions in the original notes on Github by @ whenever I got stuck. But for the most part, I was able to sail through once I got a grasp of the common math and stat functions available in the NumPy lib.

In [11]:
import numpy as np

# 1

In [13]:
#create a numpy array containing the values [1,2,3]

In [14]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [15]:
#create a two dimensional numpy array

In [16]:
b = np.array([[1,2,3],[2,3,4]])
print(b)

[[1 2 3]
 [2 3 4]]


In [17]:
#create a 3D numpy array

In [18]:
c = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  8]
  [ 9 10 11]]]


# 2

In [19]:
#check if all elements in the array are greater tha 0

In [20]:
a = np.array([1,2,3])

print(np.all(a>0))

True


In [21]:
#check if any element in the numpy array [-1,0,1] is greater than 0

In [22]:
b = np.array([-1,0,1])

print(np.any(b>0))

True


In [23]:
#check if any elements in the numpy array [[1,2],[3,4]] is greater than 0.5

In [24]:
c = np.array([[1,2],[3,4]])

print(np.any(c>0.5))

True


In [25]:
#check if any element in the array is true

In [26]:
d = np.array([-1,0,1])

print(np.any(d))

True


# 3

In [27]:
#python function taking 1D array as input and returns a copy of the array with the data type converted to int

In [28]:
a = np.array([1.,1.,6.6])

x = a.astype('int')

print("a was:", a)
print("now is:",x)

a was: [1.  1.  6.6]
now is: [1 1 6]


In [29]:
#python function taking 2D array as input and returns a copy of the array 
#with the data type converted to float

In [30]:
b = np.random.randint(1,10,(3,3))

y = b.astype('float')

print('b was:',b)
print()
print('now is:',y)

b was: [[8 8 5]
 [3 6 4]
 [5 3 7]]

now is: [[8. 8. 5.]
 [3. 6. 4.]
 [5. 3. 7.]]


In [31]:
#You have an array a of size (3,3) that contains random float values between -1 and 1. 
#create a new array b of the same size, where each element of b is clipped to a range between -0.5 and 0.5. 
#Print both arrays a and b to compare the original and clipped values.

In [32]:
a = np.random.uniform(-1,1,(3,3))

b = np.clip(a,-0.5,0.5 )

print('a is:',a)
print()
print('b is:',b)

a is: [[ 0.87080918  0.76106736  0.91790821]
 [-0.73988417 -0.6088649   0.92175379]
 [ 0.6559365   0.02813901 -0.11602005]]

b is: [[ 0.5         0.5         0.5       ]
 [-0.5        -0.5         0.5       ]
 [ 0.5         0.02813901 -0.11602005]]


In [33]:
#You have an array a of size (5,5) that contains random integer values between 1 and 100.
#create a new array b of the same size, where each element of b is clipped to a range between 
#the 25th and 75th percentile of the values in a. Print both arrays a and b to compare the original and clipped values.

In [34]:
a = np.random.randint(1,101,(5,5))

p25 = np.percentile(a, 25)
p75 = np.percentile(a, 75)

b = np.clip(a, p25,p75)

print('a is:',a)
print()
print('25th percentile of a is:', p25)
print()
print('75th percemtile of a is:', p75)
print()
print('b is:',b)

a is: [[96 99 86 67 14]
 [78 95 17 34 26]
 [95 22 34 92 59]
 [ 3 30 49 49 18]
 [55 26 21 97  3]]

25th percentile of a is: 22.0

75th percemtile of a is: 86.0

b is: [[86. 86. 86. 67. 22.]
 [78. 86. 22. 34. 26.]
 [86. 22. 34. 86. 59.]
 [22. 30. 49. 49. 22.]
 [55. 26. 22. 86. 22.]]


# 4

In [35]:
#Create an array a of size (3,3) with random integer values between 0 and 9. create a new array b that is a copy of 
#a (numpy.copy()). Modify the value of an element in b, and then print both a and b to compare the original and 
#modified values. What do you notice about the changes to b?

In [36]:
a = np.random.randint(1,10,(3,3))
print('a is:',a)
print()

b = np.copy(a)
print('OG b is:', b)
print()

b[1,2]=75
print('modified b:',b)

a is: [[7 3 6]
 [1 3 1]
 [2 1 3]]

OG b is: [[7 3 6]
 [1 3 1]
 [2 1 3]]

modified b: [[ 7  3  6]
 [ 1  3 75]
 [ 2  1  3]]


In [37]:
#Create an array a of size (5,5) with random float values between 0 and 1. create a new array b that is a copy of a. 
#Modify the values of elements in a such that they are all 1.0. Then, print both a and b to confirm that only 
#a was modified and b remains unchanged.

In [95]:
a = np.random.rand(5,5)
print('a is:\n',a)
print()

b = np.copy(a)
print('b is:\n',b)
print()

a = (a-a)+1.0 #couldn't quite figure out any other way to change all of a's elements at once using their index, 
                    #so I went with this for now.(hopefully, there's an answer for that in the task solution 😅)
    
print('modified a:\n',a)
print()
print('b is still:\n', b)

a is:
 [[0.12128006 0.33164533 0.82825713 0.88050709 0.65894989]
 [0.65524086 0.78489892 0.91303302 0.76878416 0.68053378]
 [0.33033683 0.77891225 0.32814061 0.47106281 0.79273302]
 [0.91028773 0.85208725 0.76908663 0.19786933 0.54236139]
 [0.34988914 0.80826262 0.29732361 0.7128735  0.2311459 ]]

b is:
 [[0.12128006 0.33164533 0.82825713 0.88050709 0.65894989]
 [0.65524086 0.78489892 0.91303302 0.76878416 0.68053378]
 [0.33033683 0.77891225 0.32814061 0.47106281 0.79273302]
 [0.91028773 0.85208725 0.76908663 0.19786933 0.54236139]
 [0.34988914 0.80826262 0.29732361 0.7128735  0.2311459 ]]

modified a:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

b is still:
 [[0.12128006 0.33164533 0.82825713 0.88050709 0.65894989]
 [0.65524086 0.78489892 0.91303302 0.76878416 0.68053378]
 [0.33033683 0.77891225 0.32814061 0.47106281 0.79273302]
 [0.91028773 0.85208725 0.76908663 0.19786933 0.54236139]
 [0.34988914 0.80826262 0.29732361 0.7128735  0.2311

# 5

In [39]:
#Create an array a of size (4,4) with random integer values between 1 and 10. compute the cumulative product 
#of elements in a along both axes. Print the resulting arrays to compare the intermediate and final results 
#of the cumulative product.

In [40]:
a = np.random.randint(1,11,(4,4))
print('a is:',a)
print()
cp1 = np.cumprod(a, axis=1)
cp2 = np.cumprod(a, axis=0)

print('axis 1 is:', cp1)
print()
print('axis 2 is:', cp2)


a is: [[10  1  1  7]
 [ 2  4  2  4]
 [ 6  2  7  1]
 [ 8  2  2  2]]

axis 1 is: [[10 10 10 70]
 [ 2  8 16 64]
 [ 6 12 84 84]
 [ 8 16 32 64]]

axis 2 is: [[ 10   1   1   7]
 [ 20   4   2  28]
 [120   8  14  28]
 [960  16  28  56]]


In [41]:
#Create an array a of size (3,3) with random float values between 0 and 1. compute the cumulative product 
#of elements in a along the first axis. Then, use np.sum() to compute the sum of elements in the resulting array. 
#Compare the sum to the final element of the original a.

In [42]:
a = np.random.rand(3,3)

axis1 = np.cumprod(a, axis=1)

fsum = a[:,2].sum()

print('a is:',a)
print()
print('axis 1:',axis1)
print()
print('sum of a1 elements:',fsum)

a is: [[0.11583274 0.02145875 0.2271233 ]
 [0.24221932 0.36611778 0.61579601]
 [0.28853609 0.32672523 0.25344241]]

axis 1: [[0.11583274 0.00248563 0.00056454]
 [0.24221932 0.0886808  0.05460928]
 [0.28853609 0.09427202 0.02389253]]

sum of a1 elements: 1.0963617245248014


# 6

In [43]:
#Create an array a of size (4,4) with random integer values between 1 and 10. compute the cumulative sum of 
#elements in a along both axes. Print the resulting arrays to compare the intermediate and final results of 
#the cumulative sum.

In [44]:
a = np.random.randint(1,11,(4,4))
axis1 = np.cumsum(a,axis=1)
axis2 = np.cumsum(a,axis=0)

print(a)
print()
print(axis1)
print()
print(axis2)


[[ 3 10  5  7]
 [ 5  6  2  5]
 [ 3  2  2  9]
 [ 8  4  6  6]]

[[ 3 13 18 25]
 [ 5 11 13 18]
 [ 3  5  7 16]
 [ 8 12 18 24]]

[[ 3 10  5  7]
 [ 8 16  7 12]
 [11 18  9 21]
 [19 22 15 27]]


## get back to this soon 👇🏽👇🏽👇🏽

In [45]:
#Create an array a of size (3,3) with random float values between 0 and 1. compute the cumulative sum 
#of elements in a along the second axis. Then, use np.mean() to compute the mean of elements in the resulting array. 
#Compare the mean to the final row of the original a, also the final row of the cumulative sum.

In [46]:
a = np.random.rand(3,3)
b = np.cumsum(a, axis=0)

print(a)
print()
print(b)
print()
print( np.sum(a[-1,:]))
print()
print( np.sum(b[-1,:]))





[[0.27241166 0.40751523 0.73152313]
 [0.57813848 0.83873874 0.68137408]
 [0.39805172 0.20620553 0.04341546]]

[[0.27241166 0.40751523 0.73152313]
 [0.85055015 1.24625396 1.41289722]
 [1.24860187 1.45245949 1.45631268]]

0.6476727094276274

4.157374035136968


# 7

In [47]:
#Create a 2D array a of size (5,5) with random integer values between 1 and 10. extract the main diagonal of 
#a and store it in a 1D array d. Then, compute the sum of elements in d. Compare the sum to the sum of elements 
#in the anti-diagonal of a.

In [58]:
a = np.random.randint(1,11,(5,5))
print('a is:\n',a)
print()

d = np.diagonal(a)
print('diagonal is:',d)
print()

#first attempt:
#anti_d = np.fliplr([np.diagonal(a)]) 
#result: reversed the original diagonal instead of getting the anti...

#correction
anti_d = np.diagonal(np.fliplr(a))
print('anti diagonal is:',anti_d)
print()

sumD = np.sum(d)
sumAD = np.sum(anti_d)

print('sum of diagonal is:',sumD)
print()
print('sum of anti diagonal is:',sumAD)

a is:
 [[ 6  1  2  1  8]
 [ 5  1  4  6  2]
 [ 2 10  8  8  7]
 [10  1  6  4  7]
 [ 2  6  1  4  7]]

diagonal is: [6 1 8 4 7]

anti diagonal is: [8 6 8 1 2]

sum of diagonal is: 26

sum of anti diagonal is: 25


# 8

In [56]:
#Create a 4x4 NumPy array filled with the value 7

In [62]:
a = np.full((4,4),7)
print(a)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [63]:
#Create a 2D NumPy array of size (3, 5) with all elements initialized to -1

In [64]:
a = np.full((3,5),-1)
print(a)

[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


In [65]:
#Create a NumPy array of size (2, 2) filled with the value 6. 
#Then create a new array of size (4,1) where the elements are ordered in row-major order.

In [68]:
a = np.full((2,2),6)
print(a)
print()
b = np.array([[5],[4],[3],[2],[1]])
print(np.sort(b,axis=1))


[[6 6]
 [6 6]]

[[5]
 [4]
 [3]
 [2]
 [1]]


# 9

In [69]:
#Write a function that takes a 2D numpy array as input and flattens it. The function should then return a 
#new 1D numpy array with the same elements as the flattened 2D array.

In [83]:
def flat(array):
    a = array.flatten()
    return a

a = np.random.randint(1,101,(6,6))
print('a is:\n',a)
print()
print('flattened:\n',flat(a))

a is:
 [[65 77  1 63 46 48]
 [20 59 45 47 39 38]
 [48 25 99  8 61 33]
 [25 76 16 60 81 98]
 [91 29 72 24 97 75]
 [40  3 59 47 69 84]]

flattened:
 [65 77  1 63 46 48 20 59 45 47 39 38 48 25 99  8 61 33 25 76 16 60 81 98
 91 29 72 24 97 75 40  3 59 47 69 84]


In [93]:
#Create a 3D numpy array of shape (2, 3, 4) filled with random integers. flatten the array and then reshape 
#the flattened array into a new array of shape (3, 8).

In [85]:
a = np.random.randint(1,25,(2,3,4))
print('a is:\n',a)
print()
b = a.flatten()
print('flattened:\n',b)
print()
rs = b.reshape(3,8)
print('reshaped:\n',rs)

a is:
 [[[22  6 13  4]
  [ 1  4 23  3]
  [ 8 10  3 24]]

 [[ 3  7  1  7]
  [17 18  2 18]
  [ 1 17 21 14]]]

flattened:
 [22  6 13  4  1  4 23  3  8 10  3 24  3  7  1  7 17 18  2 18  1 17 21 14]

reshaped:
 [[22  6 13  4  1  4 23  3]
 [ 8 10  3 24  3  7  1  7]
 [17 18  2 18  1 17 21 14]]


# 10

In [96]:
#Create a 1D numpy array filled with random integers. retrieve the first element of the array and store it in a variable.

In [106]:
a = np.random.randint(1,11,(1,7))
print('a is:\n',a)
print()

b = a.item(0)
print('first element in array a is:',b)

a is:
 [[2 6 8 4 3 5 6]]

first element in array a is: 2


In [108]:
#Create a 3D numpy array of shape (2, 3, 4) filled with random integers. retrieve a specific element of the 
#array and store it in a variable.

In [120]:
a = np.random.randint(1,25,(2,3,4))
print('a is:\n',a)
print()

b = a[0,1,2]
print('third element in 2nd row of first array in a is:',b)
print()

#OR

c = a.item(6)
print('third element in 2nd row of first array in a is:',c)


a is:
 [[[17  4  4 17]
  [ 2 13  3  2]
  [ 1 17 13 23]]

 [[ 8 13 13 24]
  [19 24  1  4]
  [ 5  6 10 18]]]

third element in 2nd row of first array in a is: 3

third element in 2nd row of first array in a is: 3


# 11

In [121]:
#Given a 2D array arr, find the minimum value in each row and find the maximum value in each column.

In [122]:
arr = np.random.randint(1,101,(6,6))

col_min = np.min(arr,axis=0)
row_min = np.min(arr,axis=1)

print('arr is:\n',arr)
print()
print('minimum value in each row is:\n',row_min)
print()
print('minimum value in each column is:\n',col_min)


arr is:
 [[18 42 29 28 13 15]
 [19 39 62 26 67 21]
 [25 16 12 46 12 99]
 [66 49 59 55 35 36]
 [80 58 46 26 93 40]
 [74 86 20 44 26 80]]

minimum value in each row is:
 [13 19 12 35 26 20]

minimum value in each column is:
 [18 16 12 26 12 15]


In [123]:
#Create a random array of size 10x10 using np.random.rand. find the minimum and maximum values in the entire array.

In [124]:
a = np.random.rand(10,10)

max_v = np.max(a)
min_v = np.min(a)

print('a is:\n',a)
print()
print('max value in a is:',max_v)
print()
print('min value in a is:',min_v)


a is:
 [[0.15505019 0.52725216 0.59577837 0.79754939 0.5692203  0.51579911
  0.95716836 0.95361542 0.91885134 0.6925835 ]
 [0.68998307 0.48076734 0.67567467 0.73633339 0.18310667 0.60993292
  0.73241722 0.20362442 0.14554066 0.47102093]
 [0.4053594  0.04286274 0.66167506 0.18221031 0.35984804 0.85944959
  0.27299886 0.03847685 0.3892247  0.99035465]
 [0.24145224 0.68777994 0.4284998  0.69022528 0.44742579 0.98087063
  0.11196485 0.5824324  0.30992464 0.0544414 ]
 [0.08580078 0.67832319 0.5075495  0.34320364 0.09114328 0.14684277
  0.43709758 0.06513179 0.35192091 0.1752219 ]
 [0.63382644 0.39013521 0.50830889 0.5145318  0.72424404 0.88612149
  0.86580115 0.30172431 0.24867061 0.23619005]
 [0.10677539 0.44985391 0.53634802 0.42009671 0.99434678 0.63710159
  0.23963437 0.33383495 0.15738243 0.08849655]
 [0.5739352  0.76768295 0.79570934 0.06100298 0.3208769  0.46287721
  0.9793714  0.14807468 0.55901987 0.35159485]
 [0.02932451 0.26319645 0.8673651  0.16469017 0.1702996  0.95080333
  0.2

# 12

In [125]:
#Create a numpy array a with random integers between 1 and 10. Calculate the mean of a.

In [128]:
a1 = np.random.randint(1,11,(4,6))

a1_mean = np.mean(a1)
print('a1 is:\n',a1)
print()
print('mean of array a1 is:',a1_mean)

#OR

print(f'mean of array a2 is: {np.random.randint(1,11,(4,6)).mean()}')
#refactored here ☝🏽 according to practice question solution.

a1 is:
 [[ 1  2  7  5  4  1]
 [ 4  6  9  1  3  3]
 [ 8 10  5  1  8  4]
 [ 9  5 10  4  3 10]]

mean of array a1 is: 5.125
mean of array a2 is: 4.791666666666667


In [129]:
#Create a 2D numpy array b with random floats between 0 and 1. Calculate the mean of each row and each column.

In [163]:
b = np.random.rand(4,4)

r_mean = np.mean(b,axis=1)
c_mean = np.mean(b, axis=0)

print('b is:\n',b)
print()
print('mean of rows 1-4 is:\n',r_mean)
print()
print('mean of columns 1-4 is:\n',c_mean)


b is:
 [[0.24713577 0.40184937 0.9453703  0.13854687]
 [0.66180961 0.18457082 0.11732484 0.1507988 ]
 [0.61182352 0.2252381  0.13282842 0.98430269]
 [0.5547619  0.37200783 0.79485085 0.61583839]]

mean of rows 1-4 is:
 [0.43322558 0.27862602 0.48854818 0.58436474]

mean of columns 1-4 is:
 [0.5188827  0.29591653 0.4975936  0.47237168]


(was stuck up there for a while trying to calculate the mean for each row one at a time🤦🏽‍♂️😑)

In [166]:
#Create a numpy array e of shape (4, 4) with random integers between 1 and 10. 
#Calculate the mean of the elements in the diagonal of e.